name: lukewale
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47009
title: Luke Wale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07050c'
    - '#f7fcff'
    - '#2d58a9'
    - '#3cb3d9'
    - '#95ceed'
  brandStrength: 0.493421
  lightness: 0.625
  saturation: 0.424342
  rhythmicContrast: 0.370065
purpose: []
